config/routes.rb
Rails.application.routes.draw do
  root to: "results#new"

  get "/signup", to: "users#new", as: "signup"
  get "/users/:id", to: "users#show", as: "user"
  post "/signup", to: "users#create"

  post '/login', to: "regestraitions#create"
  get '/login', to: "regestraitions#new", as: "new_regestrations"
  get '/logout', to: "regestraitions#destroy"

  get '/about', to: "static_pages#about"

  get '/', to: "results#new", as: "new_result"
  get '/:string', to: "results#show", as: "result"
  post '/', to: "results#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
    belongs_to :user, class_name: "User", foreign_key: "user_id"
    validates :full_string, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :results, class_name: "Result", foreign_key: "user_id", dependent: :destroy 
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    before_validation :normalize_email


    private
    def normalize_email
    self.email = self.email.downcase.strip
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/regestraitions_controller.rb
class RegestraitionsController < ApplicationController
  def new
    if session[:user_id]
      redirect_to root_path 
    end
  end
  def create
    @user = User.find_by(email: params[:email].downcase.strip)
    if @user
      session[:user_id] = @user.id
      redirect_to(root_path)
    else 
      redirect_to(new_regestrations_path)
    end
  end

  def destroy
    redirect_to new_regestrations_path, notice: "You need to be logged in in order to log out" and return if !session[:user_id]
    reset_session
    redirect_to new_regestrations_path
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  include ApplicationHelper 
  include ResultsHelper
  before_action :logged_in?

  def new 
    @result = Result.new
  end

  def create
    @get_result = Result.find_by(full_string: params[:full_string], user_id: session[:user_id])
    redirect_to result_path(params[:full_string]) and return if @get_result

    @sub = LongestSubstring(params[:full_string])
    @new_result = Result.new(full_string: params[:full_string], longest_sub: @sub, longest_sub_length: @sub.length, user_id: session[:user_id])
      if @new_result.save
        redirect_to result_path(params[:full_string])
      else
        render :action => "new"
      end
  end

  def show 
    @result = Result.find_by(full_string: params[:string])
    if !@result
      redirect_to root_path, notice: 'This string is not solved yet'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper 
  before_action :logged_in?, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = @user.errors.full_messages[0]
      render action: 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    redirect_to root_path, notice: "There is no such user" and return  if !@user 
    
    if @user.id != session[:user_id]
      redirect_to root_path , notice: "You shall not pass"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        unless session[:user_id] 
            redirect_to new_regestrations_path, notice: "You must be logged in"
        end
    end
end

app/helpers/results_helper.rb
module ResultsHelper
    def LongestSubstring(s)
        return s if s.length == 1
        startOfWindow = 0
        currentPosition = 0
        biggest =[]
        arr = []  
        s = s.chars
        while currentPosition < s.length
            if arr.include?(s[currentPosition]) 
                arr.delete(s[startOfWindow])
                startOfWindow += 1
            else   
                arr.push(s[currentPosition])
                currentPosition += 1
                if biggest.length <  arr.length
                biggest = arr.dup 
                end
            end
        end
    biggest.join('')
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Substring App | Mahmoud Abbas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render "partials/nav" %>

    <main class="app container">
        <%= render "partials/alerts" %>
        <%= yield %>
    </main>
</body>

</html>

app/views/partials/_alerts.html.erb
<% if notice or alert%>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
</div>
<% end %>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <%= link_to "Longest Substring", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="me-auto d-flex">
                <%= link_to "Home", root_path, class: 'nav-link text-dark'%>
                <%= link_to "About", about_path, class: 'nav-link text-dark'%>
                <%= link_to "Account", user_path(session[:user_id]), class: 'nav-link text-dark' if session['user_id']%>
            </div>
            <div class="d-flex me-5">
                <%= link_to 'Login',  new_regestrations_path, {class: 'btn btn-primary'} if !session['user_id'] %>
                <%= link_to 'Signup',  signup_path , {class: 'ms-3 btn btn-info'} if !session['user_id']%>
                <%= link_to 'Logout',  logout_path,  {class: 'ms-3 btn btn-danger'} if session['user_id'] %>
            </div>
        </div>
    </div>
</nav>

app/views/regestraitions/_form.html.erb
<div class="d-flex justify-content-center px-5 py-5 my-5">
    <%= form_with html: {class: 'w-md-50 form d-flex flex-column'} do |form| %>

    <div class="form-group mb-4">
        <label for="inputEmail" class="font-weight-bold mb-1 ">Email</label>
        <%= form.email_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}', class: 'form-control', id: 'inputEmail', placeholder: "Email" %>
    </div>

    <%= form.submit "Login", class: 'btn btn-primary btn-lg w-md-25 align-self-center'%>

    <% end %>
</div>

app/views/results/_form.html.erb
<div class="d-flex justify-content-center px-5 my-5">
    <%= form_with html: {class: 'w-md-50 form d-flex flex-column'} do |form| %>

    <div class="form-group mb-4">
        <%= form.text_field :full_string, :required => true, class: 'form-control', id: 'inputString', placeholder: "Insert the string" %>
    </div>

    <%= form.submit "Check the string", class: 'btn btn-primary btn-lg w-md-25 align-self-center'%>

    <% end %>
</div>

app/views/results/new.html.erb
<div class="d-flex flex-column justify-content-center px-5 py-5 my-5">
    <h2 class="text-center">Longest Substring</h2>
    <p class="text-center">
        Check the longest substring of the enterd string and it's length.
    </p>
    <%= render "form" %>
</div>

app/views/results/show.html.erb
<div class="d-flex flex-column  justify-content-center px-5 py-5 mx-5 my-5">
    <p><strong>Full string:</strong> <%= @result.full_string %></p>
    <p><strong>Longest substring:</strong> <%= @result.longest_sub %></p>
    <p><strong>Longest substring length:</strong> <%= @result.longest_sub_length %></p>
</div>

app/views/static_pages/about.html.erb
<div class="d-flex flex-column align-items-center my-5">
    <h1>Longest Substring</h1>
    <p>This is an example app created for explanation. The wwhole purpose of the app is to allow wa user to find the longest substring with repeating characters. </p>
</div>

app/views/users/_form.html.erb
<div class="d-flex justify-content-center px-5 py-5 my-5">
    <%= form_with model: @user,html: {class: 'w-md-50 form d-flex flex-column'}, url: signup_path do |form| %>
    <div class="form-group mb-3">
        <label for="inputName" class="mb-1">Name</label>
        <%= form.text_field :name ,:required => true, class: 'form-control', id: "inputName", placeholder: "Name"%>
    </div>
    <div class="form-group mb-4">
        <label for="inputEmail" class="font-weight-bold mb-1 ">Email</label>
        <%= form.email_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}', class: 'form-control', id: 'inputEmail', placeholder: "Email" %>
    </div>

    <%= form.submit "Sign up", class: 'btn btn-info btn-lg w-md-25 align-self-center'%>

    <% end %>
</div>

app/views/users/new.html.erb
<%= render "form" %>

app/views/users/show.html.erb
<div class="d-flex flex-column  justify-content-center px-5 py-5 mx-5 my-5">
    <h2><%= @user.name%></h2>
    <h3>Email: <%= @user.email %></h3>
    <h4>Previous results</h4>
    <ul class="list-unstyled ">
        <% @user.results.each do |el| %>
        <li class="d-flex justify-content-between mx-5 px-5">
            <p>Full string: <%= el.full_string%></p>
            <p>Longest substring: <%= el.longest_sub%></p>
            <p>longest substring length: <%= el.longest_sub_length%></p>
        </li>
        <%end%>
    </ul>
</div>